### ISSUE TITLE
This tutorial code is obselete, code does not run correctly

### ISSUE THREAD

**Issue by plastikfan** [adbertram/PowerShellModuleProject#1]
I am not expecting this to be fixed, rather it is a warning for others who come accross this tutorial, to either use their own Powershell module, that is known to work, or make some minor adjustments so that the pipeline "succeeds".

Problems are as follows:
* the azure-pipelines.yml file contains an out of date reference to an old task version.

```yaml
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: Pester@0 <---------------- PROBLEM HERE
      inputs:
        scriptFolder: "@{Path='$(System.DefaultWorkingDirectory)/PowerShellModuleProject.Tests.ps1'"
        resultsFile: "$(System.DefaultWorkingDirectory)/PowerShellModuleProject.Tests.XML"
        usePSCore: true
        run32Bit: False

```
the problem here is -Task: Pester@0 which results in the following error:

> A task is missing. The pipeline references a task called 'Pester' with version '0'. This indocates that the specific task version can not be found. (job 'Test', step ''.)

At the time of writing, the lastest version is 10, so updating this line to
> - task: Pester@10

fixes this error.

* There is another error relating to some path that can't be found. I have no idea what this is.
```
##[error]Get-ChildItem: /home/vsts/.local/share/powershell/Modules/Pester/5.0.3/Pester.psm1:3159
Line |
3159 |              Get-ChildItem -Recurse -Path $p -Filter "*$Extension" -Fi …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/@{Path='/home/vsts/work/1/s/' because it
     | does not exist.


##[error]Get-ChildItem: /home/vsts/.local/share/powershell/Modules/Pester/5.0.3/Pester.psm1:3159
Line |
3159 |              Get-ChildItem -Recurse -Path $p -Filter "*$Extension" -Fi …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/@{Path='/home/vsts/work/1/s/' because it
     | does not exist.
```

So I deleted the task and re-created it in the UI, which produced something slightly different:

```yaml
    - task: Pester@10
      inputs:
        scriptFolder: '$(System.DefaultWorkingDirectory)\*'
        resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
        usePSCore: False
```

And this works.

* Pester testcase error, using the wrong syntax for v5 Pester:

```powershell
{ Import-Module -Name "$PSScriptRoot\PowerShellModuleProject.psm1" -ErrorAction Stop } | should not throw
```

the 
> should not throw

is the problem, "not" should be "-not"

* Pester test case error (parameter binding issue, test case: "the module imports successfully")

```
[-] Module-level tests.the module imports successfully
 53ms (25ms|29ms)

 ParameterBindingException: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
 at <ScriptBlock>, /home/vsts/work/1/s/PowerShellModuleProject.Tests.ps1:6
```

I'm not that bothered about this test case or why it's failing, just either delete the test, or apply -Skip to that test case.

When all of these fixes are applied, both the Build and Test stages succeed, but the Deploy fails:

```
Starting: NuGetCommand
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.172.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
/usr/bin/msbuild /version /nologo
Caching tool: NuGet 5.4.0 x64
Found tool in cache: NuGet 5.4.0 x64
Resolved from tool cache: 5.4.0
Using version: 5.4.0
Found tool in cache: NuGet 5.4.0 x64
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
Detected NuGet version 5.4.0.6315 / 5.4.0+d790b66be476cd901a56bd46ada037162097ee21.d790b66be476cd901a56bd46ada037162097ee21
##[warning]Could not create provenance session: %s
##[warning]The feed with ID 'adbertram' doesn't exist.
/usr/bin/mono /opt/hostedtoolcache/NuGet/5.4.0/x64/nuget.exe push /home/vsts/work/1/PowerShellModuleProject.0.0.11.nupkg -NonInteractive -Source https://pkgs.dev.azure.com/winjer/_packaging/adbertram/nuget/v3/index.json -ApiKey VSTS -Verbosity Detailed
NuGet Version: 5.4.0.6315
```

This failure is perhaps more understandable, 

> ##[warning]The feed with ID 'adbertram' doesn't exist.

We probably need to define something specific to our own requirements or using own our feed ID, what-ever that means, I have no idea, I'm still working my way through this maze.

And finally a message to Adam Bertram, thanks for writing this tutorial and responding to my message on Twitter. The only issue I have is that there are no trouble shooting pointers in your tutorial, which is the case with most blog articles which makes them diffficult to follow unless you're doing the tutorial very soon after it has been written so that its not out of date. I've tried to follow, numerous blog articles with regards to Azure pipeline development for PowerShell modules and most if not all have some kind of issue with something no longer working for whatever reason.

It would have been nice if there were user comments on this article. That way, people discovering the article and running into issues can share their problems and perhaps somebody else can chip in with solutions; ie we can all help each other, so that when the code goes out of date, the community can collectively provide work-arounds and further advice. I wouldn't have had to raise this issue that actually probably no one will see.

**Comment by adbertram** [comment]
Thanks for taking the time to discover these issues. I've fixed all of them and added comments for future readers to ensure they look at some things and change them before they continue.

**Comment by plastikfan** [comment]
Thank you for responding, cheers.
