### ISSUE TITLE
Question regarding PSScriptAnalyzer

### ISSUE THREAD

**Issue by gintuoklis** [adbertram/PowerShellModuleProject#2]
Hi, 
I tried to setup CICD pipelines based on your example, and I'm experiencing issues with PSScriptAnalyzer. It fails on import-module step:

```
Import-Module -Name PSScriptAnalyzer
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module 'PSScriptAnalyzer' was not loaded because
     | no valid module file was found in any module directory.

```

I don't see any script where you install the module. Is it missing, or should it come as part of Pester or Hosted Agent?

**Comment by ahaeber** [comment]
@gintuoklis I got the same problem. But found now that the source code in https://github.com/adbertram/PowerShellModuleProject/blob/master/PowerShellModuleProject.Tests.ps1 has changed to use `Install-Module` instead:
```
Install-Module -Name PSScriptAnalyzer -Force
```

**Comment by Atreidae** [comment]
Might want to update the webpage at https://adamtheautomator.com/powershell-devops/

The code examples (which I stupidly copied and pasted instead of cloning the repo) still have the old code.

**Comment by adbertram** [comment]
Sorry for the delay on this. I've now updated the blog code to mirror the GitHub repo.
